variables:
- name: ReleaseEnvironmentName
  value: prd-draft
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: cosmosDbCollectionName
  value: job-groups-draft
- name: sharedContentDbCollectionName
  value: shared-content-draft
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.JobGroups
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-jobgroups-draft
- name: contentUrl
  value: $(ContentApiDraftAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-prd-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/jobgroups-draft
- name: apiName
  value: jobgroups-draft
- name: apiId
  value: composite-ui-jobgroups-draft
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-prd-draft-app-jobgroups
- name: SubscriptionSettingsFilterIncludeEventTypes3
  value: draft
- name: SubscriptionSettingsFilterIncludeEventTypes4
  value: draft-discarded
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
  value: 2c9da1b3-3529-4834-afc9-9cd741e59788
- name: EnableAzureMonitorAlerting
  value: true
- name: clientAffinity
  value: false
- name: jobgroupsAppDatabaseThroughput
  value: 1200
- name: ExceptionCountThreshold
  value: 10
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-prd-draft-app-jobgroups-as.$(FunctionAppDomain)/lmi-delta-report
- name: EventGridSubjectPrefix
  value: /dfc-app-jobgroups/
- name: ContentMode
  value: DRAFT