variables:
- name: ReleaseEnvironmentName
  value: prd
- name: AppServiceName
  value: $(WebAppPrefix)-as-ver2
- name: AppServicePlanSuffix
  value: -migrated
- name: cosmosDbCollectionName
  value: job-groups
- name: sharedContentDbCollectionName
  value: shared-content
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.JobGroups
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-jobgroups
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-prd-api-eventgridsubscriptions-fa-ver2.$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/jobgroups
- name: apiName
  value: jobgroups
- name: apiId
  value: composite-ui-jobgroups
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-prd-app-jobgroups
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
  value: 2c9da1b3-3529-4834-afc9-9cd741e59788
- name: EnableAzureMonitorAlerting
  value: true
- name: clientAffinity
  value: false
- name: jobgroupsAppDatabaseThroughput
  value: 1200
- name: ExceptionCountThreshold
  value: 10
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-prd-app-jobgroups-as-ver2.$(FunctionAppDomain)/lmi-delta-report
- name: EventGridSubjectPrefix
  value: /dfc-app-jobgroups/
- name: ContentMode
  value: PUBLISHED
- name: Expiry
  value: 4